name: CI
on:
  push:
  pull_request:

# Some orgs require this; harmless elsewhere
permissions:
  contents: read
  actions: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose ./README.md ./index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./.lighthouserc.json
          runs: 1
          # Workaround: disable GitHub artifact upload (avoids 400)
          uploadArtifacts: false
          # Keep temporary public storage so you still get a shareable report URL
          temporaryPublicStorage: true
