name: CI
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Link check (Markdown + HTML)
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose ./README.md ./index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Lighthouse CI against static dist (this repo)
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          staticDistDir: .
          runs: 1
          uploadArtifacts: true
          temporaryPublicStorage: true
